import React, { useState, useEffect, useRef } from 'react'
import { fetch } from '../utils/fetch';
import { useParams } from 'react-router-dom';
import { Link } from 'react-router-dom';
import { exportComponentAsJPEG } from 'react-component-export-image';



const GeneratedContent = React.forwardRef((props, ref) => {
    const { name } = useParams()
    const [content, setContent] = useState('');

    useEffect(() => {
        // console.log(process.env.REACT_APP_OPENAI_API_KEY)
        fetch(name).then((data) => setContent(data.choices[0].text))
    }, [name])

    const handleGenerateNew = (e) => {
        e.preventDefault()
        setContent('')
        fetch(name).then((data) => setContent(data.choices[0].text))
    }

    return (<>
        <div className='navbar'>
            <div className='button-grp' style={{ background: 'none' }}>
                <Link to="/"><button>Back</button></Link>
                <button onClick={handleGenerateNew}>Generate new</button>
            </div>
        </div>
        <div className='content-box' ref={ref} >
            {content ? content : "Loading ... "}
            <br />
            <span style={{ color: 'grey', fontSize: '10px' }}>
                Generated By: text-davinci-003
            </span>
        </div>

    </>

    )
})

const Content = () => {
    const componentRef = useRef();

    return (
        <>

            <GeneratedContent ref={componentRef} />
            <div className='button-grp' style={{ justifyContent: 'center' }}>
                <button onClick={() => exportComponentAsJPEG(componentRef)}>Download</button>
            </div>
            <p style={{ marginTop: 50, marginLeft: 50, fontFamily: "Montserrat,sans-serif", fontWeight: "900" }}>
                Fan Theories can be really bizzare and may not be related at all to the series or book as they are generated by AI. Don't blame the Developer for it.
            </p>
        </>
    );
};


export default Content