import React from 'react'
import { categories } from '../utils/constants'
import { Link } from 'react-router-dom'
const Home = () => {
    return (<>
        <div className='navbar'>

            <h1 style={{ margin: 0, marginLeft: 50, fontFamily: "Montserrat,sans-serif", fontWeight: "900", fontSize: "40px" }}>fanfic <span style={{fontSize:"20px",fontWeight: "500"}}>- fan theories generated by AI</span></h1>

        </div>
        <div className='box'>
            {categories.map((item, idx) => (

                <div className='items' key={idx}>
                    <Link to={`/${item.name}`}>
                        <img src={item.img} alt={item.name} />
                        <p>{item.name}</p>
                    </Link>

                </div>
            ))
            }
        </div >
    </>

    )
}

export default Home